name: Code Quality

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run formatter
        run: npm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run linter
        run: npm run lint:check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --no-watch --code-coverage --browsers=ChromeHeadless

      - name: Generate Code Coverage Summary Report
        id: code_coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/apl-golf-league/cobertura-coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && hashFiles('code-coverage-summary.md') != ''
        with:
          header: code-coverage
          path: ./code-coverage-summary.md
          recreate: true

      - name: Upload HTML Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/apl-golf-league/
